import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {cn} from "@/shared/ui/utils";
import {ReactQueryClientProvider} from "@/shared/providers";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReactQueryClientProvider>
            <html lang="en" className="h-full w-full" suppressHydrationWarning style={{scrollbarGutter: "stable"}}>
            <body className={cn(inter.className, "h-full w-full")}>
            <div className="flex-grow bg-muted/40 min-h-full  md:h-full">
                <div className="flex-grow h-full w-full p-3 ">
                    {children}
                </div>
            </div>
            </body>
            </html>
        </ReactQueryClientProvider>
    );
}
